import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { Document, Types } from "mongoose";
@Schema()
export class News extends Document{
    
    // Generated by https://quicktype.io
    @Prop()
    title?:          string;
    @Prop()
    creator?:        string;
    @Prop()
    link?:           string;
    @Prop()
    pubDate?:        string;
    @Prop()
    content?:        string;
    @Prop()
    contentSnippet?: string;
    @Prop()
    guid?:           string;
    @Prop()
    isoDate?:        string;

    @Prop({type:Object})

    enclosure?:any;

    @Prop({ type: Types.ObjectId, ref: 'Rss' }) // Referencia al modelo de RSS
    rss: Types.ObjectId;
    
}

export const NewsSchema = SchemaFactory.createForClass(News);
